// <auto-generated />
using System;
using API.ETEC01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.ETEC01.Migrations
{
    [DbContext(typeof(APIETEC01Context))]
    [Migration("20210307202514_InicialCriacao")]
    partial class InicialCriacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.ETEC01.Model.ContaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataDoPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDoVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDoCredor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValoraPagar")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ContaModel");
                });
#pragma warning restore 612, 618
        }
    }
}
